CFLAGS = -std=c99 -Wall -Wextra -D_GNU_SOURCE
CC = gcc
GDB = gdb
BUILD_DIR = build
RAYLIB_DIR = vendor/raylib/src
RAYLIB_CFLAGS = PLATFORM=PLATFORM_DESKTOP
BUILD_MODE = RELEASE

# game
GAME_BINARY = igario
GAME_CFLAGS = $(CFLAGS)
GAME_INCLUDES = -isystem $(RAYLIB_DIR)
GAME_OPTIONS = -DOS_IMPLEMENTATION_LINUX -DMEMORY_MMAP -DLOG_IMPLEMENTATION -DARENA_IMPLEMENTATION
GAME_LDLIBS = -L$(RAYLIB_DIR) -l:libraylib.a -lGL -lm -lpthread -ldl -lrt -lX11

# server
SERVER_BINARY = server
SERVER_CFLAGS = $(CFLAGS)
SERVER_INCLUDES = -isystem $(RAYLIB_DIR)/external
SERVER_OPTIONS = -DOS_IMPLEMENTATION_LINUX -DMEMORY_MMAP -DLOG_IMPLEMENTATION -DARENA_IMPLEMENTATION -DRPRAND_IMPLEMENTATION
SERVER_LDLIBS = -lm -lpthread

.PHONY: build game server generate deps clean

ifeq ($(BUILD_MODE),DEBUG)
    CFLAGS += -g -O0 -DDEBUG
	RAYLIB_CFLAGS += RAYLIB_BUILD_MODE=DEBUG
endif

ifeq ($(BUILD_MODE),RELEASE)
    CFLAGS += -Os
	RAYLIB_CFLAGS += RAYLIB_BUILD_MODE=RELEASE
endif

build: server game

game: deps generate $(GAME_BINARY).c
	$(CC) $(GAME_BINARY).c -o $(BUILD_DIR)/$(GAME_BINARY) $(GAME_CFLAGS) -I$(BUILD_DIR) $(GAME_INCLUDES) $(GAME_LDLIBS) $(GAME_OPTIONS)

server: deps generate $(SERVER_BINARY).c
	$(CC) $(SERVER_BINARY).c -o $(BUILD_DIR)/$(SERVER_BINARY) $(SERVER_CFLAGS) -I$(BUILD_DIR) $(SERVER_INCLUDES) $(SERVER_LDLIBS) $(SERVER_OPTIONS)

generate:
	mkdir -p $(BUILD_DIR)/generated

deps:
	$(MAKE) -C $(RAYLIB_DIR) $(RAYLIB_CFLAGS)

clean:
	$(MAKE) -C $(RAYLIB_DIR) clean
	$(RM) -rf $(BUILD_DIR)
